---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: default
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: grafana-np
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
  labels:
    app: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: default
      protocol: TCP
