---
- name: Run node-exporter container
  docker_container:
    name: prometheus-exporter
    image: prom/node-exporter
    state: started
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
    command: "-collector.procfs /host/proc -collector.sysfs /host/proc -collector.filesystem.ignored-mount-points '^/(sys|proc|dev|host|etc)($|/)'"
