---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      # Scrape the Node Exporter every 5 seconds.
      - job_name: "node"
        scrape_interval: 5s
        static_configs:
          - targets: 
              - ":9100"
              - ":9100"
